name: ${project.name}
author: Nikl
main: me.nikl.calendarevents.CalendarEvents
version: ${project.version}
website: nikl.me
api-version: '1.14'

softdepend: [PlaceholderAPI]

commands:
  calendarevents:
    description: main command
    usage: /calendarevents
    aliases: [ce]

permissions:
  calendarevents.reload:
    description: Gives permission to use the reload command
    default: op
  calendarevents.help:
    description: Gives permission to use the help command
    default: true
  calendarevents.list:
    description: Gives permission to use the list command
    default: true
